/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polysfactory_n3_unity_NativeMarkerDetector */

#ifndef _Included_com_polysfactory_n3_unity_NativeMarkerDetector
#define _Included_com_polysfactory_n3_unity_NativeMarkerDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_polysfactory_n3_unity_NativeMarkerDetector
 * Method:    nativeFindMarkers
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_n3_unity_NativeMarkerDetector_nativeFindMarkers
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
